### ISSUE TITLE
Vita version update breaks compatibility

### ISSUE THREAD

**Issue by vladone97** [Arks-Layer/PSO2ENPatchCSV#617]
Yesterday, the Vita version of the game received an update which caused most of the translation patch to not work anymore. The main menu, the server select menu and the character select menu are still in English, but in-game, pretty much everything else that used to be translated is now in Japanese.

**Comment by Aida-Enna** [comment]
The vita version breaks every few updates because of how SEGA arranges the files on the vita. I don't actively play the vita version (aside from testing etc) so I've been looking for someone to ping me in the vita discord channel whenever it breaks so I can fix it. If you'd like to be that hero, join the #vita-pso2 channel of our discord (http://discord.gg/PSO2). If not, that's okay! I'm also working on methods to automate building the patch, because right now the entire process is done manually. Either way, this kind of stuff should be posted there (as it's not an actual issue with the translation) in the future, so I'll go ahead and close this. Thanks!
